services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    env_file: ./.env
    networks:
      - infra

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    env_file: ./.env
    ports:
      - '9092:9092'
    networks:
      - infra
    depends_on:
      - zookeeper

  mongo:
    image: mongo
    restart: always
    env_file: ./.env
    ports:
      - 27017:27017
    networks:
      - infra

  postgres:
    image: postgres:12-alpine
    restart: always
    env_file: ./.env
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - infra

  account:
    build:
      context: ./account
    restart: always
    env_file: ./account/.env
    ports:
      - 8080:8080
    networks:
      - backend
    depends_on:
      - broker
      - mongo

  account_view:
    build:
      context: ./account_view
    restart: always
    env_file: ./account_view/.env
    ports:
      - 8081:8081
    networks:
      - backend
    depends_on:
      - broker
      - postgres

volumes:
  db-data:

networks:
  infra:
  backend:
